title: Alhad Barbadikar # your name (or website title) here
logo: "/images/20190614_091123.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Looking for an entry level job in Data Science & then hopefully a better understanding of the world. Life becomes easier to live with when you're on a quest. Mine is to be less ignorant. What's yours?
  <br><br>
  <a href="https://www.linkedin.com/in/alhadbarbadikar/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-144840443-1 # your Google Analytics tracking ID here
